### ISSUE TITLE
Links in list don't open

### ISSUE THREAD

**Issue by compuguy** [awans/giftr-sandstorm#3]
The optional links in the list, do not open in a sandstorm grain with a traditional left click. The only way to open them is via a right click and open in a new tab.

**Comment by ocdtrekkie** [comment]
This is a super easy fix, I can send a PR. Or you can, if you want. In Sandstorm, external links must open in new tabs. The feature was added here: https://github.com/awans/giftr-sandstorm/commit/ff4829bba975f735d6dff521df6d33bb3854cca0 and all we need is a `target="_blank"` in that link tag.
