### ISSUE TITLE
Reorder list

### ISSUE THREAD

**Issue by ocdtrekkie** [awans/giftr-sandstorm#8]
I know Giftr isn't getting any development right now, but I wanted to note my feature request: I find it kinda weird I can't reorder my wish list, ideally with drag and drop.

**Comment by akumansley** [comment]
Thanks for the suggestion! You're right that I'm not actively maintaining giftr-sandstorm. If you know someone who'd be interested, I'd be happy to hand it over :)

**Comment by ocdtrekkie** [comment]
I'd love to fix it up here and there someday, but I'm a bit behind on my Sandstorm app todo list already.

I am about to start actually personally using this app on my server, so we'll see if I get motivated to dig in.
